### ISSUE TITLE
Log In

### ISSUE THREAD

**Issue by greghelton** [ACloudGuru/acloudguru#1]
Using the acloud.guru log-in screen, 16 hours ago I requested a password reset link but I never got one.  I have since tried dozens of times and I still have not received an email with a password reset link.  Can you fix that please?

**Comment by johncmckim** [comment]
Hi @greghelton we did have a problem with the Auth0 lock widget a few days ago. It might be worth clearing your cache and trying again.

If you still have problem can you please email support@acloud.guru?
